on:
  push:
    branches:
      - main
  pull_request:
name: CI/CD
jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm install -g firebase-tools
      - run: firebase target:apply hosting app listmeow
      - run: firebase deploy --only hosting:app --token ${{ secrets.FIREBASE_TOKEN }}
