name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    env:
      GOOGLE_APPLICATION_CREDENTIALS: google-application-credentials.json

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        shell: bash
        run: npm ci

      - name: Prepare Google Application Credentials
        shell: bash
        run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" | base64 --decode > "google-application-credentials.json"

      - name: Deploy Firebase functions
        shell: bash
        run: npm run deploy

      - name: Remove credentials file
        if: success() || failure()
        run: |
          rm google-application-credentials.json
